### PR TITLE
Initial Nix Support

### PR DESCRIPTION
**Pull request by TheOPtimal**
This PR uses Crane to build the project with Nix. Currently, the tests (`nix flake check`) are failing because it found 2 vulnerable crates being used as dependencies. Additionally, the flake template I added has a bunch of convenient tests, which we can put into GitHub Actions and get effortless, declarative CI.

I'll add the NixOS module in a later PR.

### CODE REVIEW

**Comment by TheOPtimal** [comment]
Here is the failing check log:

```log
cargoVendorDir not set, will not automatically configure vendored sources
cargoArtifacts not set, will not reuse any cargo artifacts
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/la4891v6kwq9kx6hix44xy95qanbn1ad-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
Executing configureCargoCommonVars
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
default configurePhase, nothing to do
@nix { "action": "setPhase", "phase": "buildPhase" }
building
++ command cargo --version
cargo 1.64.0
++ command cargo audit -n -d /nix/store/ndpc8wa7p6imzhd8zwayn12h8vd8hx8k-source
      Loaded 469 security advisories (from /nix/store/ndpc8wa7p6imzhd8zwayn12h8vd8hx8k-source)
warning: couldn't open crates.io index: registry: failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
    Scanning Cargo.lock for vulnerabilities (403 crate dependencies)
Crate:     chrono
Version:   0.4.19
Title:     Potential segfault in `localtime_r` invocations
Date:      2020-11-10
ID:        RUSTSEC-2020-0159
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution:  Upgrade to >=0.4.20
Dependency tree:
chrono 0.4.19
├── shadow-rs 0.11.0
│   └── nu-command 0.64.0
│       └── nu-discord-bot 0.2.0
├── serenity 0.11.2
│   └── nu-discord-bot 0.2.0
├── reedline 0.7.0
│   ├── nu-command 0.64.0
│   └── nu-cli 0.64.0
│       └── nu-discord-bot 0.2.0
├── procfs 0.12.0
│   └── nu-system 0.64.0
│       └── nu-command 0.64.0
├── nu-system 0.64.0
├── nu-protocol 0.64.0
│   ├── nu-table 0.64.0
│   │   ├── nu-command 0.64.0
│   │   └── nu-color-config 0.64.0
│   │       ├── nu-command 0.64.0
│   │       └── nu-cli 0.64.0
│   ├── nu-parser 0.64.0
│   │   ├── nu-discord-bot 0.2.0
│   │   ├── nu-command 0.64.0
│   │   └── nu-cli 0.64.0
│   ├── nu-engine 0.64.0
│   │   ├── nu-discord-bot 0.2.0
│   │   ├── nu-command 0.64.0
│   │   └── nu-cli 0.64.0
│   ├── nu-discord-bot 0.2.0
│   ├── nu-command 0.64.0
│   ├── nu-color-config 0.64.0
│   └── nu-cli 0.64.0
├── nu-parser 0.64.0
├── nu-engine 0.64.0
├── nu-command 0.64.0
├── nu-cli 0.64.0
├── dtparse 1.3.0
│   └── nu-command 0.64.0
├── chrono-tz 0.6.1
│   └── nu-command 0.64.0
└── chrono-humanize 0.2.1
    ├── nu-protocol 0.64.0
    └── nu-command 0.64.0

Crate:     time
Version:   0.1.44
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.44
└── chrono 0.4.19
    ├── shadow-rs 0.11.0
    │   └── nu-command 0.64.0
    │       └── nu-discord-bot 0.2.0
    ├── serenity 0.11.2
    │   └── nu-discord-bot 0.2.0
    ├── reedline 0.7.0
    │   ├── nu-command 0.64.0
    │   └── nu-cli 0.64.0
    │       └── nu-discord-bot 0.2.0
    ├── procfs 0.12.0
    │   └── nu-system 0.64.0
    │       └── nu-command 0.64.0
    ├── nu-system 0.64.0
    ├── nu-protocol 0.64.0
    │   ├── nu-table 0.64.0
    │   │   ├── nu-command 0.64.0
    │   │   └── nu-color-config 0.64.0
    │   │       ├── nu-command 0.64.0
    │   │       └── nu-cli 0.64.0
    │   ├── nu-parser 0.64.0
    │   │   ├── nu-discord-bot 0.2.0
    │   │   ├── nu-command 0.64.0
    │   │   └── nu-cli 0.64.0
    │   ├── nu-engine 0.64.0
    │   │   ├── nu-discord-bot 0.2.0
    │   │   ├── nu-command 0.64.0
    │   │   └── nu-cli 0.64.0
    │   ├── nu-discord-bot 0.2.0
    │   ├── nu-command 0.64.0
    │   ├── nu-color-config 0.64.0
    │   └── nu-cli 0.64.0
    ├── nu-parser 0.64.0
    ├── nu-engine 0.64.0
    ├── nu-command 0.64.0
    ├── nu-cli 0.64.0
    ├── dtparse 1.3.0
    │   └── nu-command 0.64.0
    ├── chrono-tz 0.6.1
    │   └── nu-command 0.64.0
    └── chrono-humanize 0.2.1
        ├── nu-protocol 0.64.0
        └── nu-command 0.64.0

Crate:     ansi_term
Version:   0.12.1
Warning:   unmaintained
Title:     ansi_term is Unmaintained
Date:      2021-08-18
ID:        RUSTSEC-2021-0139
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0139
Dependency tree:
ansi_term 0.12.1
└── lscolors 0.9.0
    └── nu-command 0.64.0
        └── nu-discord-bot 0.2.0

Crate:     dotenv
Version:   0.15.0
Warning:   unmaintained
Title:     dotenv is Unmaintained
Date:      2021-12-24
ID:        RUSTSEC-2021-0141
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0141
Dependency tree:
dotenv 0.15.0
└── nu-discord-bot 0.2.0

Crate:     failure
Version:   0.1.8
Warning:   unmaintained
Title:     failure is officially deprecated/unmaintained
Date:      2020-05-02
ID:        RUSTSEC-2020-0036
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0036
Dependency tree:
failure 0.1.8
└── pwd 1.3.1
    └── nu-path 0.64.0
        ├── nu-test-support 0.64.0
        │   └── nu-command 0.64.0
        │       └── nu-discord-bot 0.2.0
        ├── nu-parser 0.64.0
        │   ├── nu-discord-bot 0.2.0
        │   ├── nu-command 0.64.0
        │   └── nu-cli 0.64.0
        │       └── nu-discord-bot 0.2.0
        ├── nu-engine 0.64.0
        │   ├── nu-discord-bot 0.2.0
        │   ├── nu-command 0.64.0
        │   └── nu-cli 0.64.0
        ├── nu-command 0.64.0
        └── nu-cli 0.64.0

Crate:     net2
Version:   0.2.37
Warning:   unmaintained
Title:     `net2` crate has been deprecated; use `socket2` instead
Date:      2020-05-01
ID:        RUSTSEC-2020-0016
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0016
Dependency tree:
net2 0.2.37
├── miow 0.2.2
│   └── mio 0.6.23
│       ├── notify 4.0.17
│       │   └── nu-command 0.64.0
│       │       └── nu-discord-bot 0.2.0
│       └── mio-extras 2.0.6
│           └── notify 4.0.17
└── mio 0.6.23

error: 2 vulnerabilities found!
warning: 4 allowed warnings found
```

**Comment by tanishqkancharla** [comment]
It says 
```
error: 2 vulnerabilities found!
warning: 4 allowed warnings found
```

Do you know which ones are the allowed warnings and which dependencies are causing the vulnerabilities?

**Comment by tanishqkancharla** [comment]
After looking at the RUST SEC reports, it seems the most important crates to upgrade are `failure`, `time` and `chrono`.

**Comment by TheOPtimal** [comment]
chrono and time are the vulnerable ones, the rest are just deprecated.

**Comment by tanishqkancharla** [comment]
`failure`'s SEC report says it's a "critical" issue even though its just been deprecated; is that fine?

**Comment by TheOPtimal** [comment]
> `failure`'s SEC report says it's a "critical" issue even though its just been deprecated; is that fine?

It should still be fixed, but the more important ones are chrono and time, since they have actual vulnerabilities

**Comment by TheOPtimal** [comment]
Any updates on this? This is ready to be merged

**Comment by tanishqkancharla** [comment]
I think updating all our dependencies will be enough; I don't see a dependency on chrono 0.4.19 from any of the nushell crates. 

However, updating to the latest nushell crates gives me the following error, which I can't find anything on the internet about:
```sh
error: failed to run custom build command for `libproc v0.12.0`

Caused by:
  process didn't exit successfully: `/Users/tanishqkancharla/Documents/Projects/nubot/target/debug/build/libproc-3bd9e6f2288d83b0/build-script-build` (exit status: 101)
  --- stderr
  /Users/tanishqkancharla/.cargo/registry/src/github.com-1ecc6299db9ec823/libproc-0.12.0/libproc_rs.h:1:10: fatal error: 'libproc.h' file not found
  /Users/tanishqkancharla/.cargo/registry/src/github.com-1ecc6299db9ec823/libproc-0.12.0/libproc_rs.h:1:10: fatal error: 'libproc.h' file not found, err: true
  thread 'main' panicked at 'Failed to build libproc bindings: ()', /Users/tanishqkancharla/.cargo/registry/src/github.com-1ecc6299db9ec823/libproc-0.12.0/build.rs:9:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by tanishqkancharla** [comment]
Got it working and updated the deps as much as I can; let me know if there's something else to be done.

**Comment by TheOPtimal** [comment]
> Got it working and updated the deps as much as I can; let me know if there's something else to be done.

The tests still fail, but the package itsself builds. The PR is ready to merge, we can deal with the failing tests later.

**Comment by tanishqkancharla** [comment]
Are you referring to the unit tests in this package? Or something else?

**Comment by TheOPtimal** [comment]
> Are you referring to the unit tests in this package? Or something else?

I'm referring to the Nix tests, the one that audits the package along with everything else

**Pull request merged**
